### ISSUE TITLE
prosafe_exporter no longer works with current Prometheus version

### ISSUE THREAD

**Issue by acuntex** [dalance/prosafe_exporter#226]
The prosafe_exporter does not seem to work anymore with current Prometheus versions.

The error Prometheus shows is:
`Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target`

**Comment by dalance** [comment]
I fixed it. Could you try the latest master?

**Comment by dalance** [comment]
In my environment, it works fine with Prometheus v3.

**Comment by dalance** [comment]
> Are you interested in a pull request? You would just have to create a classic personal token with write:packages and put it in this repo as secret as GHCR_TOKEN and make the GCHR public so that there's always a current official docker image when you create a release.

Yes, please.
I'll merge the PR, and release a new version.

**Comment by dalance** [comment]
I released v0.2.9.

**Comment by acuntex** [comment]
Great, thanks, would you also make https://ghcr.io/dalance/prosafe_exporter public so users could consume it? :-)

**Comment by dalance** [comment]
I changed the visibility. How about it?

**Comment by acuntex** [comment]
Awesome, you're the best! :-)
