### ISSUE TITLE
Building for arm64/aarch64 fails

### ISSUE THREAD

**Issue by ginkel** [dalance/prosafe_exporter#34]
Hi there,

I am attempting to build prosafe_exporter for arm64/aarch64. Unfortunately, this fails due to an incompatibility in nix 0.10.0, which gets pulled in via interfaces2:

```
[...]
   Compiling tokio-buf v0.1.1
   Compiling string v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling url v2.2.0
error[E0425]: cannot find value `MAP_32BIT` in crate `libc`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.10.0/src/sys/mman.rs:49:9
   |
49 |         MAP_32BIT;
   |         ^^^^^^^^^ not found in `libc`
   Compiling toml v0.5.7
   Compiling bincode v1.3.1
   Compiling tokio-timer v0.2.13
   Compiling tokio-current-thread v0.1.7
error: aborting due to previous error
For more information about this error, try `rustc --explain E0425`.
error: could not compile `nix`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I would have opened an issue over there, but interfaces2 has disabled the issue tracker... Maybe you have an idea how to work around this issue or avoid the usage of interfaces2.

Thanks!

**Comment by ginkel** [comment]
To ease with reproducing the issue: My build looks like this:

`Dockerfile.aarch64`:
```
FROM messense/rust-musl-cross:aarch64-musl as builder

RUN set -x \
  && git clone https://github.com/dalance/prosafe_exporter.git \
  && cd prosafe_exporter \
  && cargo build --target=aarch64-unknown-linux-musl --release
```

```
docker build -f Dockerfile.aarch64 .
```

**Comment by dalance** [comment]
Thank you for your report.
I created pull request to fix it https://github.com/aep/interfaces-rs/pull/1.
If there is no response, I'll consider to fork it or use another crate.

**Comment by dalance** [comment]
I took over the maintenance of the original interfaces crate, and released the fixed version.

**Comment by ginkel** [comment]
LGTM, thanks a lot!
