### ISSUE TITLE
Exporter not thread-safe?

### ISSUE THREAD

**Issue by ginkel** [dalance/prosafe_exporter#6]
Hi there,

thanks for building this exporter. In our setup we have two Prometheus instances (for redundancy), both with identical configuration, which scrape the prosafe_exporter that is deployed as a single instance on our network (close to the switches).

Everything works fine as long as only a single Prometheus instance is scraping the exporter. As soon as we start the second instance, the `prosafe_up` metric very often comes back as `0` and the other metrics are missing.

Could it be that the prosafe_exporter is not thread-safe?

Thanks,
Thilo

P.S.: Our current workaround is to deploy two instances, one for each Prometheus instance.

**Comment by dalance** [comment]
Thanks!
A part of exporter was not thread-safe.
I fixed it and released v0.2.4.
Could you try it?

**Comment by ginkel** [comment]
LGTM, thanks for the speedy fix! :smile:
